# Generated by Django 3.0.8 on 2020-07-21 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200720_1432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tools',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='tools',
            old_name='Title',
            new_name='link',
        ),
        migrations.AddField(
            model_name='tools',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='tools',
            name='title',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
