# Generated by Django 3.0.8 on 2020-07-21 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200721_0538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tools',
            name='image',
            field=models.FileField(default=None, null=True, upload_to=''),
        ),
    ]
