# Generated by Django 3.0.8 on 2020-07-21 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200721_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tools',
            name='image',
            field=models.FileField(upload_to='tools/'),
        ),
    ]
