# Generated by Django 3.0.8 on 2020-07-21 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_news_projects'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
        migrations.DeleteModel(
            name='Projects',
        ),
        migrations.DeleteModel(
            name='Tools',
        ),
    ]
