# Generated by Django 3.0.8 on 2020-07-21 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20200721_0811'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('link', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=40000)),
                ('image', models.FileField(upload_to='news/')),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('link', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=40000)),
                ('image', models.FileField(upload_to='projects/')),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('link', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=40000)),
                ('image', models.FileField(upload_to='tools/')),
            ],
        ),
    ]
