# Generated by Django 3.0.8 on 2020-07-21 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20200721_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='color',
            field=models.CharField(choices=[('Student_projects', 'Student projects'), ('Testbeds ', 'Testbeds')], default='Student projects', max_length=200),
        ),
    ]
