# Generated by Django 3.0.8 on 2020-07-22 05:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20200721_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
