# Generated by Django 3.0.8 on 2020-07-22 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20200722_0550'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='created_at',
            new_name='modified_at',
        ),
        migrations.AddField(
            model_name='news',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tools',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
